spring:
  application:
    name: tvmaze-middleware
  mongodb:
    uri: ${MONGO_URI}
    database: tvmaze
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

tvmaze:
  api:
    base-url: https://api.tvmaze.com