spring:
  application:
    name: tvmaze-test
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: tvmaze
  jackson:
    default-property-inclusion: non_null
tvmaze:
  api:
    base-url: https://api.tvmaze.com
server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs